function saved(d){let s=localStorage.getItem(key(d));return s?JSON.parse(s):null}
function draft(d){let s=localStorage.getItem(draftKey(d));return s?JSON.parse(s):null}
function previousRows(d){let p=shiftDate(d,-1);return saved(p)||draft(p)||((p==='2026-09-01')?clone(BASE):null)}
function freshFromPrevious(d){let prev=previousRows(d);if(prev)return prev.map(r=>({name:r.name,start:n(r.actual),cases:0,caseSize:n(r.caseSize),sales:0,actual:0}));let blank=clone(BASE);blank.forEach(r=>{r.start=0;r.cases=0;r.sales=0;r.actual=0});return blank}
function defaultForDate(d){if(d==='2026-09-01')return clone(BASE);return freshFromPrevious(d)}
function persist(){localStorage.setItem(draftKey(currentDate),JSON.stringify(rows))}
function openDate(d){currentDate=d;let s=saved(d),q=draft(d);rows=s||q||defaultForDate(d);if(!s&&!q&&d===TODAY)persist();render();updateDateTabs()}
function input(i,k,v){rows[i][k]=n(v);persist();render()}
function updateDateTabs(){yesterdayText.textContent=shortDate(YESTERDAY);todayText.textContent=shortDate(TODAY);yesterdayBtn.classList.toggle('active',currentDate===YESTERDAY);todayBtn.classList.toggle('active',currentDate===TODAY)}
function render(){let th=0,ac=0,mi=0,ba=0;rows.forEach(r=>{th+=theory(r);ac+=n(r.actual);mi+=missing(r);if(missing(r)!==0)ba++});sCount.textContent=rows.length;sTheory.textContent=th;sActual.textContent=ac;sMissing.textContent=mi;sBad.textContent=ba;view==='daily'?renderDaily():renderPack()}
function renderDaily(){tabDaily.classList.add('active');tabPack.classList.remove('active');let mobile=innerWidth<=850;thead.innerHTML=mobile?'<tr><th>品名</th><th>初始</th><th>进货</th><th>剩余</th><th>销量</th><th>漏单</th><th>状态</th></tr>':'<tr><th>品名</th><th>初始库存（瓶）</th><th>进货总瓶数</th><th>剩余库存（瓶）</th><th>销量（瓶）</th><th>漏单（瓶）</th><th>状态</th></tr>';tbody.innerHTML=rows.map((r,i)=>{let m=missing(r);return `<tr><td>${r.name}</td><td><input inputmode="numeric" value="${r.start}" onchange="input(${i},'start',this.value)"></td><td class="auto">${incoming(r)}</td><td><input inputmode="numeric" value="${r.actual}" onchange="input(${i},'actual',this.value)"></td><td><input inputmode="numeric" value="${r.sales}" onchange="input(${i},'sales',this.value)"></td><td class="${m?'bad':''}">${m}</td><td><span class="badge ${m?'badgeBad':''}">${m?'异常':'正常'}</span></td></tr>`}).join('');let sum=f=>rows.reduce((a,r)=>a+f(r),0);tfoot.innerHTML=`<tr><td>合计</td><td>${sum(r=>n(r.start))}</td><td>${sum(incoming)}</td><td>${sum(r=>n(r.actual))}</td><td>${sum(r=>n(r.sales))}</td><td>${sum(missing)}</td><td>—</td></tr>`;formula.textContent='漏单 = 初始库存 + 进货总瓶数 − 销量 − 剩余库存'}
function renderPack(){tabDaily.classList.remove('active');tabPack.classList.add('active');thead.innerHTML='<tr><th>品名</th><th>单件瓶数</th><th>订货件数</th><th>进货总瓶数</th></tr>';tbody.innerHTML=rows.map((r,i)=>`<tr><td>${r.name}</td><td><input inputmode="numeric" value="${r.caseSize}" onchange="input(${i},'caseSize',this.value)"></td><td><input inputmode="numeric" value="${r.cases}" onchange="input(${i},'cases',this.value)"></td><td class="auto">${incoming(r)}</td></tr>`).join('');tfoot.innerHTML='';formula.textContent='进货总瓶数 = 单件瓶数 × 当天订货件数'}
function switchTab(v){view=v;render()}
function saveDay(){localStorage.setItem(key(currentDate),JSON.stringify(rows));localStorage.setItem(draftKey(currentDate),JSON.stringify(rows));toastMsg(`已保存 ${shortDate(currentDate)}`)}
function newDay(){currentDate=TODAY;rows=freshFromPrevious(TODAY);localStorage.setItem(draftKey(TODAY),JSON.stringify(rows));render();updateDateTabs();toastMsg('已新建今日日盘：初始继承昨日，剩余为0')}
function carryYesterday(){let prev=previousRows(currentDate);if(!prev)return toastMsg('没有上一日记录');let mp=Object.fromEntries(prev.map(r=>[r.name,r]));rows.forEach(r=>{let p=mp[r.name];if(p){r.start=n(p.actual);r.caseSize=n(p.caseSize)||r.caseSize}r.cases=0;r.sales=0;r.actual=0});persist();render();toastMsg('已继承上一日剩余到初始')}
function resetCurrent(){let s=saved(currentDate);rows=s?clone(s):defaultForDate(currentDate);localStorage.setItem(draftKey(currentDate),JSON.stringify(rows));render();toastMsg(s?'已恢复最近保存':'已恢复默认日盘')}
const ALIASES={'小噜渴':'LOOK','小鹿可':'LOOK','噜渴':'LOOK','look':'LOOK','LOOK':'LOOK','上海力波':'力波白啤','力波':'力波白啤','力波白啤':'力波白啤','超级勇闯':'超级勇闯','勇闯':'超级勇闯','大窑橙诺':'大窑橙诺','橙诺':'大窑橙诺'};
function norm(s,group){let t=s.trim();if(group===2&&t.includes('白啤'))return '30白啤';if(ALIASES[t])return ALIASES[t];let f=rows.find(r=>t.includes(r.name)||r.name.includes(t));if(f)return f.name;for(let k in ALIASES)if(t.toLowerCase().includes(k.toLowerCase()))return ALIASES[k];return t}
function addParsed(name,qty,group,totals,unmatched){name=norm(name,group);let r=rows.find(x=>x.name===name);if(r)totals[name]=(totals[name]||0)+Number(qty);else unmatched.push(name)}
function parseGeneric(text,group,totals,unmatched){let src=text.replace(/[，,；;\n]+/g,' '),re=/(\d+(?:\.\d+)?)\s*(?:件|箱)\s*([^0-9\s]+)|([^0-9\s]+?)\s*(\d+(?:\.\d+)?)\s*(?:件|箱)/g,m;while((m=re.exec(src))!==null){if(m[1])addParsed(m[2],m[1],group,totals,unmatched);else addParsed(m[3],m[4],group,totals,unmatched)}}
function parseGroup2(text,totals,unmatched){let src=text.replace(/\s+/g,''),rules=[['30白啤','白啤'],['椰子水','椰子水']],cleaned=src;for(let [target,label] of rules){let qty=0,a=[...src.matchAll(new RegExp('(\\d+(?:\\.\\d+)?)\\s*(?:件|箱)\\s*'+label,'g'))],b=[...src.matchAll(new RegExp(label+'\\s*(\\d+(?:\\.\\d+)?)\\s*(?:件|箱)','g'))];a.forEach(m=>qty+=Number(m[1]));b.forEach(m=>qty+=Number(m[1]));if(qty>0){totals[target]=(totals[target]||0)+qty;cleaned=cleaned.replace(new RegExp('\\d+(?:\\.\\d+)?(?:件|箱)'+label,'g'),'').replace(new RegExp(label+'\\d+(?:\\.\\d+)?(?:件|箱)','g'),'')}}if(cleaned)parseGeneric(cleaned,2,totals,unmatched)}
function parseOrders(){let t1=orderText1.value.trim(),t2=orderText2.value.trim();if(!t1&&!t2)return toastMsg('先粘贴订货信息');let totals={},un=[];parseGeneric(t1,1,totals,un);parseGroup2(t2,totals,un);rows.forEach(r=>r.cases=0);let out=[];Object.entries(totals).forEach(([name,q])=>{let r=rows.find(x=>x.name===name);if(r){r.cases=q;out.push(`${name}${q}件→${incoming(r)}瓶`)}});persist();render();parseResult.textContent=out.length?'已识别：'+out.join('；')+(un.length?'。未匹配：'+[...new Set(un)].join('、'):''):'没有识别到订货内容'}
function clearOrders(){orderText1.value='';orderText2.value='';parseResult.textContent=''}
function showHistory(){let a=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k&&k.startsWith(STORE+'-')&&!k.includes('-draft-'))a.push(k.replace(STORE+'-',''))}alert(a.length?'已保存日期：\n'+a.sort().join('\n'):'暂无历史记录')}
function deleteDay(){if(!confirm('确定删除 '+shortDate(currentDate)+' 的日盘？'))return;localStorage.removeItem(key(currentDate));localStorage.removeItem(draftKey(currentDate));rows=defaultForDate(currentDate);persist();render()}
function exportImage(){try{const W=980,rowH=34,topH=170,H=topH+(rows.length+2)*rowH+40,c=document.createElement('canvas');c.width=W;c.height=H;let x=c.getContext('2d');x.fillStyle='#08111d';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='bold 28px -apple-system,PingFang SC,sans-serif';x.fillText('酒水日盘',28,42);x.font='15px -apple-system,PingFang SC,sans-serif';x.fillStyle='#9fb0c4';x.fillText('日期：'+currentDate,28,68);let sum=f=>rows.reduce((a,r)=>a+f(r),0),stats=[['品项',rows.length],['理论库存',sum(theory)],['实际库存',sum(r=>n(r.actual))],['总漏单',sum(missing)],['异常品项',rows.filter(r=>missing(r)!==0).length]];stats.forEach((s,i)=>{let bx=28+i*184;x.fillStyle='#101c2a';x.fillRect(bx,88,170,54);x.fillStyle='#95a8bd';x.font='12px sans-serif';x.fillText(s[0],bx+10,108);x.fillStyle='#fff';x.font='bold 20px sans-serif';x.fillText(String(s[1]),bx+10,134)});let cols=[28,190,315,440,565,690,800],heads=['品名','初始库存','进货总瓶数','剩余库存','销量','漏单','状态'],widths=[162,125,125,125,125,110,140],y=topH;x.font='bold 13px sans-serif';heads.forEach((h,i)=>{x.fillStyle='#122033';x.fillRect(cols[i],y,widths[i],rowH);x.fillStyle='#dce8f4';x.fillText(h,cols[i]+8,y+22)});rows.forEach((r,ri)=>{y+=rowH;let m=missing(r),vals=[r.name,n(r.start),incoming(r),n(r.actual),n(r.sales),m,m===0?'正常':'异常'];vals.forEach((v,i)=>{x.fillStyle=ri%2?'#0c1722':'#0d1825';x.fillRect(cols[i],y,widths[i],rowH);x.fillStyle=(i>=5&&m!==0)?'#ff6969':(i===6?'#58da77':'#eef4fb');x.font='13px sans-serif';x.fillText(String(v),cols[i]+8,y+22)})});resultImage.src=c.toDataURL('image/png');imgModal.classList.add('show')}catch(e){toastMsg('图片生成失败')}}