function emptyDuck(){return {initial:0,made:0,sales:0,after:0,remain:0}}
function normalizeDuck(v){return Object.assign(emptyDuck(),v||{})}
function openDuckDate(d){duckDate=d;let s=localStorage.getItem(duckKey(d)),q=localStorage.getItem(duckKey(d)+'-draft');if(!s&&!q&&d===TODAY){let ys=localStorage.getItem(duckKey(YESTERDAY)),yq=localStorage.getItem(duckKey(YESTERDAY)+'-draft'),yd=normalizeDuck(ys?JSON.parse(ys):(yq?JSON.parse(yq):null));duck=emptyDuck();duck.initial=n(yd.remain);localStorage.setItem(duckKey(TODAY)+'-draft',JSON.stringify(duck))}else duck=normalizeDuck(s?JSON.parse(s):(q?JSON.parse(q):null));renderDuck();duckYesterdayText.textContent=shortDate(YESTERDAY);duckTodayText.textContent=shortDate(TODAY);duckYesterdayBtn.classList.toggle('active',d===YESTERDAY);duckTodayBtn.classList.toggle('active',d===TODAY)}
function updateDuck(k,v){duck[k]=n(v);localStorage.setItem(duckKey(duckDate)+'-draft',JSON.stringify(duck));renderDuck()}
function updateDuckMade(el){let v=n(el.value);if(v<0||v%12!==0){toastMsg('制作量必须是12的倍数');el.value=n(duck.made);return}updateDuck('made',v)}
function renderDuck(){duck=normalizeDuck(duck);duckInitial.value=n(duck.initial);duckMade.value=n(duck.made);duckSales.value=n(duck.sales);duckAfter.value=n(duck.after);duckRemain.value=n(duck.remain);let available=n(duck.initial)+n(duck.made),sold=n(duck.sales)+n(duck.after),leak=available-sold-n(duck.remain);dProduction.textContent=available;dSalesTotal.textContent=sold;dLeak.textContent=leak;dLeakCard.classList.toggle('bad',leak!==0);duckStatus.textContent=leak===0?`核对正常：${available} = ${sold+n(duck.remain)}，鸭血无遗漏`:`存在差异：${leak>0?'少了':'多了'} ${Math.abs(leak)} 份`}
function saveDuck(){localStorage.setItem(duckKey(duckDate),JSON.stringify(duck));localStorage.setItem(duckKey(duckDate)+'-draft',JSON.stringify(duck))}
function saveDuckImage(){if(n(duck.made)%12!==0)return toastMsg('制作量必须是12的倍数');saveDuck();try{const W=760,H=610,c=document.createElement('canvas');c.width=W;c.height=H;let x=c.getContext('2d');x.fillStyle='#08111d';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='bold 30px -apple-system,PingFang SC,sans-serif';x.fillText('鸭血日盘',32,48);x.font='16px -apple-system,PingFang SC,sans-serif';x.fillStyle='#9fb0c4';x.fillText('日期：'+duckDate,32,78);let available=n(duck.initial)+n(duck.made),sold=n(duck.sales)+n(duck.after),leak=available-sold-n(duck.remain),stats=[['总量',available],['销售总量',sold],['漏单',leak]];stats.forEach((s,i)=>{let bx=32+i*228;x.fillStyle='#101c2a';x.fillRect(bx,105,208,76);x.fillStyle='#95a8bd';x.font='14px sans-serif';x.fillText(s[0],bx+14,131);x.fillStyle=i===2&&leak!==0?'#ff6969':'#fff';x.font='bold 28px sans-serif';x.fillText(String(s[1]),bx+14,166)});let items=[['初始量',n(duck.initial)],['制作量',n(duck.made)],['当天销售量',n(duck.sales)],['过0点销售量',n(duck.after)],['余量',n(duck.remain)]];let y=220;x.font='16px sans-serif';items.forEach((it,i)=>{x.fillStyle=i%2?'#0c1722':'#0d1825';x.fillRect(32,y,696,54);x.fillStyle='#b6c5d5';x.fillText(it[0],50,y+33);x.fillStyle='#fff';x.font='bold 20px sans-serif';x.fillText(String(it[1]),620,y+33);x.font='16px sans-serif';y+=54});x.fillStyle=leak===0?'#58da77':'#ff6969';x.font='bold 18px -apple-system,PingFang SC,sans-serif';x.fillText(leak===0?`${available} = ${sold+n(duck.remain)}，鸭血无遗漏`:'核对异常：差异 '+leak+' 份',32,525);x.fillStyle='#9fb0c4';x.font='14px -apple-system,PingFang SC,sans-serif';x.fillText('漏单 = 初始量 + 制作量 − 当天销售量 − 过0点销售量 − 余量',32,565);resultImage.src=c.toDataURL('image/png');imgModal.classList.add('show');toastMsg('图片已生成，长按保存到照片')}catch(e){toastMsg('图片生成失败')}}
function resetDuck(){let s=localStorage.getItem(duckKey(duckDate));duck=normalizeDuck(s?JSON.parse(s):null);renderDuck();toastMsg(s?'已恢复最近保存':'已清零')}
function duckHistory(){let a=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k&&k.startsWith(DUCK_STORE+'-')&&!k.endsWith('-draft'))a.push(k.replace(DUCK_STORE+'-',''))}alert(a.length?'鸭血已保存日期：\n'+a.sort().join('\n'):'暂无鸭血历史记录')}