let salesFiles={today:[],after:[]},auditFiles=[];
function pickSalesImages(type,input){salesFiles[type]=[...input.files];let p=document.getElementById(type+'Preview'),state=document.getElementById(type+'FileState');state.textContent=salesFiles[type].length?`已选择 ${salesFiles[type].length} 张图片`:'未选择图片';if(salesFiles[type][0]){p.src=URL.createObjectURL(salesFiles[type][0]);p.style.display='block'}else p.style.display='none'}
function pickAuditImages(input){auditFiles=[...input.files];let p=document.getElementById('auditPreview'),state=document.getElementById('auditFileState');state.textContent=auditFiles.length?`已选择 ${auditFiles.length} 张图片`:'未选择图片';if(auditFiles[0]){p.src=URL.createObjectURL(auditFiles[0]);p.style.display='block'}else p.style.display='none'}
const OCR_NAMES=[['雪花纯生',['雪花纯生']],['超级勇闯',['超级勇闯']],['百威',['百威']],['喜力',['喜力']],['老雪花',['老雪花']],['青岛',['青岛1903','青岛']],['乌毡帽',['乌毡帽']],['大窑荔爱',['大窑荔爱']],['大窑橙诺',['大窑橙诺']],['北冰洋',['北冰洋']],['听可乐',['听可乐','可乐']],['听雪碧',['听雪碧']],['无糖可乐',['无糖可乐']],['王老吉',['王老吉']],['果粒橙',['果粒橙']],['大可乐',['大可乐']],['大雪碧',['大雪碧']],['矿泉水',['矿泉水']],['唯怡豆奶',['唯怡豆奶','唯怡']],['椰子水',['椰子水']],['光明酸奶',['光明酸奶']],['30白啤',['鲜啤30公里白啤','30公里白啤','30白啤']],['力波白啤',['力波白啤','上海力波']],['小郎酒',['小郎酒']],['古越龙山',['古越龙山']],['LOOK',['LOOK','小鹿可','小噜渴']]];
const AUDIT_ROW_NAMES=['雪花纯生','超级勇闯','百威','喜力','老雪花','青岛','乌毡帽','大窑荔爱','大窑橙诺','北冰洋','听可乐','听雪碧','无糖可乐','王老吉','果粒橙','大可乐','大雪碧','矿泉水','唯怡豆奶','椰子水','光明酸奶','30白啤','力波白啤','小郎酒','古越龙山'];
function matchOcrName(line){for(let [name,aliases] of OCR_NAMES){if(aliases.some(a=>line.toLowerCase().includes(a.toLowerCase())))return [name,aliases]}return null}
function cleanAuditLine(s){return s.replace(/[|｜¦]/g,' ').replace(/[OoＯ]/g,'0').replace(/[Ilｌ]/g,'1').replace(/\s+/g,' ').trim()}
function auditNums(s){return [...s.matchAll(/\d{1,4}/g)].map(m=>Number(m[0]))}
function extractAuditRows(text){let lines=text.split(/\n+/).map(cleanAuditLine).filter(Boolean),out={};for(let line of lines){let m=matchOcrName(line);if(!m)continue;let seg=line;m[1].sort((a,b)=>b.length-a.length).forEach(a=>seg=seg.replace(new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),' '));let nums=auditNums(seg),v=null;if(nums.length>=5)v={start:nums[0],incoming:nums[1],actual:nums[2],sales:nums[3],missing:nums[4]};else if(nums.length===4)v={start:nums[0],incoming:0,actual:nums[1],sales:nums[2],missing:nums[3]};else if(nums.length===3)v={start:nums[0],incoming:0,actual:nums[1],sales:nums[2],missing:0};if(v)out[m[0]]=v}return out}
async function loadAuditCanvas(file){return new Promise((resolve,reject)=>{let img=new Image();img.onload=()=>{let c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);URL.revokeObjectURL(img.src);resolve(c)};img.onerror=reject;img.src=URL.createObjectURL(file)})}
function cropCanvas(src,x,y,w,h,scale=2){let c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));let g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(src,x,y,w,h,0,0,c.width,c.height);return c}
async function ocrDigits(canvas){let r=await Tesseract.recognize(canvas,'eng',{tessedit_char_whitelist:'0123456789',preserve_interword_spaces:'1'}),m=r.data.text.match(/\d{1,4}/);return m?Number(m[0]):0}
async function extractFixedAudit(file,onProgress){let src=await loadAuditCanvas(file),W=src.width,H=src.height;
  // This importer is for the fixed Feishu share image: table occupies roughly x 4%-96%, y 3%-94%; 1 header + 25 equal data rows.
  let left=W*.04,right=W*.96,top=H*.03,bottom=H*.94,rowH=(bottom-top)/26;
  // Column boundaries measured from the fixed six-column layout: name | start | incoming | remaining | sales | missing.
  let rel=[0,.165,.335,.505,.675,.835,1],xs=rel.map(v=>left+(right-left)*v),out={};
  for(let i=0;i<AUDIT_ROW_NAMES.length;i++){let y=top+rowH*(i+1),vals=[];for(let col=1;col<=5;col++){let padX=(xs[col+1]-xs[col])*.12,padY=rowH*.12,cell=cropCanvas(src,xs[col]+padX,y+padY,(xs[col+1]-xs[col])-padX*2,rowH-padY*2,3);vals.push(await ocrDigits(cell))}out[AUDIT_ROW_NAMES[i]]={start:vals[0],incoming:vals[1],actual:vals[2],sales:vals[3],missing:vals[4]};if(onProgress)onProgress(i+1,AUDIT_ROW_NAMES.length)}return out}
async function recognizeYesterdayAudit(){if(!auditFiles.length)return toastMsg('先上传昨天的酒水盘点图片');let result=document.getElementById('auditImportResult');result.textContent='正在按表格逐行识别 25 个品项…';try{let parsed=await extractFixedAudit(auditFiles[0],(i,total)=>result.textContent=`正在识别 ${i}/${total}…`),yRows=saved(YESTERDAY)||draft(YESTERDAY)||defaultForDate(YESTERDAY),count=0;yRows.forEach(r=>{let v=parsed[r.name];if(!v)return;r.start=n(v.start);r.sales=n(v.sales);r.actual=n(v.actual);r.cases=n(r.caseSize)?n(v.incoming)/n(r.caseSize):0;count++});localStorage.setItem(key(YESTERDAY),JSON.stringify(yRows));localStorage.setItem(draftKey(YESTERDAY),JSON.stringify(yRows));let tRows=saved(TODAY)||draft(TODAY)||defaultForDate(TODAY),ym=Object.fromEntries(yRows.map(r=>[r.name,r]));tRows.forEach(r=>{if(ym[r.name])r.start=n(ym[r.name].actual)});localStorage.setItem(draftKey(TODAY),JSON.stringify(tRows));if(saved(TODAY))localStorage.setItem(key(TODAY),JSON.stringify(tRows));if(currentDate===YESTERDAY)rows=clone(yRows);else if(currentDate===TODAY)rows=clone(tRows);render();updateDateTabs();result.textContent=`已按固定表格识别 ${count} 个品项。昨天剩余库存已同步为今天初始库存。请先核对昨天表格后再继续。`;toastMsg('25项表格识别完成')}catch(e){console.error(e);result.textContent='固定表格识别失败，请确认上传的是完整的飞书日盘表格截图';toastMsg('识别失败')}}
function extractDuckAudit(text){let t=text.replace(/[：:]/g,':').replace(/\s+/g,' ');const grab=(labels)=>{for(let label of labels){let re=new RegExp(label+'\\s*[:：]?\\s*(\\d{1,4})','i'),m=t.match(re);if(m)return Number(m[1])}return null};let initial=grab(['初始量','初始']),made=grab(['制作量','制作']),sales=grab(['当天销售量','今日销售量','当天销售','今日销售']),remain=grab(['余量','剩余量','剩余']);if(initial==null||made==null||sales==null||remain==null){let lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);for(let line of lines){let nums=[...line.matchAll(/\d{1,4}/g)].map(m=>Number(m[0]));if(!nums.length)continue;if(initial==null&&/初始/.test(line))initial=nums[nums.length-1];else if(made==null&&/制作/.test(line))made=nums[nums.length-1];else if(sales==null&&/(当天|今日).*销售/.test(line))sales=nums[nums.length-1];else if(remain==null&&/(余量|剩余)/.test(line))remain=nums[nums.length-1]}}return {initial,made,sales,remain};}
function importYesterdayDuckText(){let input=document.getElementById('duckAuditText'),result=document.getElementById('duckAuditImportResult'),text=(input?.value||'').trim();if(!text)return toastMsg('先粘贴昨天的鸭血统计文字');let parsed=extractDuckAudit(text);if(parsed.initial==null||parsed.made==null||parsed.sales==null||parsed.remain==null){result.textContent='没有识别完整，请检查文字里是否包含初始量、制作量、当天销售量、余量';return toastMsg('鸭血数据不完整')}let yDuck={initial:n(parsed.initial),made:n(parsed.made),sales:n(parsed.sales),after:0,remain:n(parsed.remain)};localStorage.setItem(duckKey(YESTERDAY),JSON.stringify(yDuck));localStorage.setItem(duckKey(YESTERDAY)+'-draft',JSON.stringify(yDuck));let ts=localStorage.getItem(duckKey(TODAY)),tq=localStorage.getItem(duckKey(TODAY)+'-draft'),tDuck=normalizeDuck(ts?JSON.parse(ts):(tq?JSON.parse(tq):null));tDuck.initial=n(yDuck.remain);localStorage.setItem(duckKey(TODAY)+'-draft',JSON.stringify(tDuck));if(ts)localStorage.setItem(duckKey(TODAY),JSON.stringify(tDuck));if(duckDate===YESTERDAY){duck=normalizeDuck(yDuck);renderDuck()}else if(duckDate===TODAY){duck=normalizeDuck(tDuck);renderDuck()}let left=n(yDuck.initial)+n(yDuck.made),right=n(yDuck.sales)+n(yDuck.remain),leak=left-right;result.textContent=`已写入昨天：初始量 ${yDuck.initial}；制作量 ${yDuck.made}；当天销售量 ${yDuck.sales}；余量 ${yDuck.remain}。${left}=${right}${leak===0?'，鸭血无遗漏':'，差异 '+leak+' 份'}。今天初始量已自动同步为 ${yDuck.remain}。`;toastMsg('昨天鸭血已写入，今天初始量已同步')}
function extractSales(text){let lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),out={};for(let i=0;i<lines.length;i++){for(let [name,aliases] of OCR_NAMES){if(aliases.some(a=>lines[i].includes(a))){let scope=lines.slice(i,Math.min(lines.length,i+3)).join(' '),nums=[...scope.matchAll(/\b(\d{1,3})\b/g)].map(m=>Number(m[1]));if(nums.length)out[name]=Math.max(...nums)}}}return out}
async function recognizeSales(type){let fs=salesFiles[type];if(!fs.length)return toastMsg('先选择截图');ocrResult.textContent='正在识别，请稍候…';let totals={};try{for(let f of fs){let r=await Tesseract.recognize(f,'chi_sim+eng');let got=extractSales(r.data.text);Object.entries(got).forEach(([k,v])=>totals[k]=(totals[k]||0)+v)}let out=[];for(let [name,v] of Object.entries(totals)){let r=rows.find(x=>x.name===name);if(!r)continue;if(type==='today')r.sales=v;else r.actual=n(r.actual)+v;out.push(`${name}${v}`)}persist();render();ocrResult.textContent=out.length?(type==='today'?'今日销量已写入：':'过0点销量已加回剩余：')+out.join('；'):'没有识别到酒水销量，请手动填写';toastMsg(out.length?'识别完成':'未识别到有效数据')}catch(e){ocrResult.textContent='识别失败，请重试或手动填写';toastMsg('识别失败')}}