// 美团管家酒水销量导入：优先读取“品项销售统计”单日导出，未知酒水不自动写入。
const MEITUAN_SALES_ALIASES={'雪花纯生':'雪花纯生','超级勇闯':'超级勇闯','百威':'百威','喜力':'喜力','老雪花':'老雪花','青岛1903':'青岛','青岛1903啤酒':'青岛','青岛啤酒':'青岛','大窑荔爱':'大窑荔爱','大窑橙诺':'大窑橙诺','听北冰洋':'北冰洋','听可乐':'听可乐','听雪碧':'听雪碧','无糖可乐':'无糖可乐','王老吉':'王老吉','果粒橙':'果粒橙','大可乐':'大可乐','大雪碧':'大雪碧','哇哈哈纯净水':'矿泉水','娃哈哈纯净水':'矿泉水','唯怡豆奶':'唯怡豆奶','椰子水':'椰子水','光明LOOK酸奶300克':'LOOK','光明酸奶':'LOOK','光明LOOK酸奶':'LOOK','光明look酸奶':'LOOK','LOOK酸奶':'LOOK','look':'LOOK','鲜啤30公里白啤':'30白啤','30公里白啤':'30白啤','上海力波精酿白啤1L':'力波白啤','力波白啤1L':'力波白啤','古越龙山黄酒':'古越龙山'};
const CUSTOM_SALES_ALIAS_KEY=STORE+'-sales-aliases-v1';
function tidySalesName(value){return String(value||'').replace(/[【】\[\]（）()]/g,'').replace(/\s+/g,'').trim()}
function cleanSalesAlias(value){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,80)}
function customSalesAliases(){try{const aliases=typeof localStorage==='undefined'?{}:JSON.parse(localStorage.getItem(CUSTOM_SALES_ALIAS_KEY)||'{}');return aliases&&typeof aliases==='object'&&!Array.isArray(aliases)?aliases:{}}catch{return {}}}
function canonicalSalesName(value){const source=cleanSalesAlias(value),aliases={...MEITUAN_SALES_ALIASES,...customSalesAliases()};if(aliases[source])return aliases[source];const tidy=tidySalesName(source),exact=Object.keys(aliases).find(key=>tidySalesName(key)===tidy);if(exact)return aliases[exact];const local=rows.find(row=>tidySalesName(row.name)===tidy);return local?local.name:null}
function saveSalesAlias(){const input=document.getElementById('salesAliasInput'),target=document.getElementById('salesAliasTarget'),state=document.getElementById('salesAliasResult'),alias=cleanSalesAlias(input?.value),canonical=String(target?.value||'');if(!alias||!rows.some(row=>row.name===canonical)){state.textContent='请输入别名并选择统一酒水品名。';return}const aliases=customSalesAliases();aliases[alias]=canonical;localStorage.setItem(CUSTOM_SALES_ALIAS_KEY,JSON.stringify(aliases));input.value='';state.textContent='已将“'+alias+'”统一识别为“'+canonical+'”。后续美团导入与文本粘贴都会使用此映射。';toastMsg('酒水别名已保存')}
function parseMeituanSales(text){const matched={},unmatched=[],invalid=[];let total=0;String(text||'').split(/\r?\n/).forEach(line=>{const clean=line.trim();if(!clean)return;const hit=clean.match(/^(.*?)(?:\s|\t|：|:)+(\d+(?:\.\d+)?)\s*$/);if(!hit){invalid.push(clean);return}const name=hit[1].trim(),quantity=n(hit[2]);if(!name||quantity<0){invalid.push(clean);return}total+=quantity;const canonical=canonicalSalesName(name);if(!canonical){unmatched.push(name);return}matched[canonical]=(matched[canonical]||0)+quantity});return {matched,unmatched:[...new Set(unmatched)],invalid,total}}
function isPossibleDrinkName(value){return /啤|酒|可乐|雪碧|王老吉|北冰洋|饮料|果汁|酸梅|椰|矿泉|纯净水|豆奶|酸奶|茶|水/.test(String(value||''))}
function parseMeituanReportRows(items){const matched={},unmatched=[],invalid=[];let total=0;for(const item of items||[]){const name=String(item?.name||'').trim(),quantity=Number(item?.quantity);if(!name||!Number.isFinite(quantity)||quantity<0){invalid.push(name||'空白品项');continue}const canonical=canonicalSalesName(name);if(canonical){matched[canonical]=(matched[canonical]||0)+quantity;total+=quantity}else if(isPossibleDrinkName(name))unmatched.push(name)}return {matched,unmatched:[...new Set(unmatched)],invalid,total}}
function xlsxColumnNumber(ref){const letters=String(ref||'').replace(/\d/g,'').toUpperCase();return [...letters].reduce((value,letter)=>value*26+letter.charCodeAt(0)-64,0)}
function xlsxCellText(cell,shared){const type=cell.getAttribute('t'),inline=cell.querySelector('is t')?.textContent;if(type==='inlineStr')return inline||'';const raw=cell.querySelector('v')?.textContent||'';return type==='s'?(shared[Number(raw)]||''):raw}
function parseMeituanXlsxSheet(xml,shared=[]){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('xlsx_xml_invalid');const grid=[...doc.querySelectorAll('sheetData row')].map(row=>[...row.querySelectorAll('c')].reduce((cells,cell)=>{cells[xlsxColumnNumber(cell.getAttribute('r'))-1]=xlsxCellText(cell,shared);return cells},[]));const filter=grid[1]?.[0]||'',dateHit=filter.match(/营业日期【(\d{4})\/(\d{2})\/(\d{2})-(\d{4})\/(\d{2})\/(\d{2})】/),headerIndex=grid.findIndex(row=>row.includes('菜品名称')&&row.includes('销售数量'));if(!dateHit||headerIndex<0)throw Error('xlsx_layout_invalid');const start=`${dateHit[1]}-${dateHit[2]}-${dateHit[3]}`,end=`${dateHit[4]}-${dateHit[5]}-${dateHit[6]}`,nameIndex=grid[headerIndex].indexOf('菜品名称'),quantityIndex=grid[headerIndex].indexOf('销售数量'),salesIndex=grid[headerIndex].indexOf('销售金额(元)'),incomeIndex=grid[headerIndex].indexOf('销售收入(元)'),discountIndex=grid[headerIndex].indexOf('优惠金额(元)');const items=grid.slice(headerIndex+1).map(row=>({name:row[nameIndex],quantity:row[quantityIndex],sales:row[salesIndex],income:row[incomeIndex],discount:row[discountIndex]})).filter(item=>String(item.name||'').trim()&&String(item.quantity||'').trim()!==''&&item.name!=='合计');return {start,end,filter:String(filter),items}}
async function unzipXlsxEntry(buffer,name){const bytes=new Uint8Array(buffer),view=new DataView(buffer);for(let offset=bytes.length-22;offset>=Math.max(0,bytes.length-65557);offset--){if(view.getUint32(offset,true)!==0x06054b50)continue;const directoryOffset=view.getUint32(offset+16,true),entries=view.getUint16(offset+10,true);let cursor=directoryOffset;for(let index=0;index<entries;index++){if(view.getUint32(cursor,true)!==0x02014b50)throw Error('xlsx_zip_invalid');const method=view.getUint16(cursor+10,true),compressed=view.getUint32(cursor+20,true),fileNameLength=view.getUint16(cursor+28,true),extraLength=view.getUint16(cursor+30,true),commentLength=view.getUint16(cursor+32,true),localOffset=view.getUint32(cursor+42,true),fileName=new TextDecoder().decode(bytes.slice(cursor+46,cursor+46+fileNameLength));if(fileName===name){if(view.getUint32(localOffset,true)!==0x04034b50)throw Error('xlsx_zip_invalid');const localNameLength=view.getUint16(localOffset+26,true),localExtraLength=view.getUint16(localOffset+28,true),data=bytes.slice(localOffset+30+localNameLength+localExtraLength,localOffset+30+localNameLength+localExtraLength+compressed);if(method===0)return new TextDecoder().decode(data);if(method!==8||typeof DecompressionStream==='undefined')throw Error('xlsx_compression_unsupported');return new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).text()}cursor+=46+fileNameLength+extraLength+commentLength}break}throw Error('xlsx_entry_missing')}
async function parseMeituanXlsxFile(file){if(!file||!/\.xlsx$/i.test(file.name))throw Error('xlsx_file_required');const buffer=await file.arrayBuffer(),sharedXml=await unzipXlsxEntry(buffer,'xl/sharedStrings.xml').catch(()=>''),shared=sharedXml?[...new DOMParser().parseFromString(sharedXml,'application/xml').querySelectorAll('sst si')].map(node=>node.textContent||''):[];return parseMeituanXlsxSheet(await unzipXlsxEntry(buffer,'xl/worksheets/sheet1.xml'),shared)}
const salesImportKey=date=>STORE+'-meituan-sales-import-'+date;
const salesCorrectionKey=date=>STORE+'-meituan-sales-corrections-'+date;
const businessAnalysisKey=date=>STORE+'-meituan-business-analysis-'+date;
function cleanSalesSourceText(value){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+$/gm,'').trim().slice(0,12000)}
function salesImportRecord(date=currentDate){try{const stored=localStorage.getItem(salesImportKey(date));if(!stored)return null;const parsed=JSON.parse(stored);return parsed&&parsed.fingerprint?parsed:{fingerprint:stored,importedAt:null,items:null,total:null}}catch{return null}}
function salesCorrectionRecords(date=currentDate){try{const parsed=JSON.parse(localStorage.getItem(salesCorrectionKey(date))||'[]');return Array.isArray(parsed)?parsed:[]}catch{return []}}
function sourceSummary(record){return {fingerprint:String(record?.fingerprint||'').slice(0,12000),source:String(record?.source||'').slice(0,80),businessDate:String(record?.businessDate||''),importedAt:String(record?.importedAt||''),items:Number(record?.items)||0,total:Number(record?.total)||0}}
function recordSalesCorrection(previous,replacement){const records=salesCorrectionRecords();records.push({changedAt:new Date().toISOString(),reason:'manual_full_report_override',previous:sourceSummary(previous),replacement:sourceSummary(replacement)});localStorage.setItem(salesCorrectionKey(currentDate),JSON.stringify(records.slice(-20)))}
function businessAnalysisRecord(date=currentDate){try{const record=JSON.parse(localStorage.getItem(businessAnalysisKey(date))||'null');return record&&Array.isArray(record.items)?record:null}catch{return null}}
function buildBusinessAnalysis(items){const clean=(items||[]).map(item=>({name:cleanSalesAlias(item.name),quantity:Number(item.quantity),sales:Number(item.sales),income:Number(item.income),discount:Number(item.discount)})).filter(item=>item.name&&[item.quantity,item.sales,item.income,item.discount].every(Number.isFinite));const sum=field=>clean.reduce((total,item)=>total+item[field],0);const top=field=>[...clean].sort((a,b)=>b[field]-a[field]).slice(0,5);return {items:clean.length,quantity:sum('quantity'),sales:sum('sales'),income:sum('income'),discount:sum('discount'),topSales:top('sales'),topQuantity:top('quantity'),topDiscount:top('discount')};}
function writeMeituanSales(result,{reportDate,source,sourceText}){const state=document.getElementById('meituanSalesResult'),names=Object.keys(result.matched),fingerprint=sourceText.replace(/\s+/g,' ');if(currentDate!==YESTERDAY){state.textContent='完整营业日销售只能写入“昨天”。请先切换到“昨天”，再导入美团管家报表。';return}if(reportDate!==YESTERDAY){state.textContent='美团报表日期必须是 '+YESTERDAY+' 的完整营业日；当前文件或日期不一致，未写入。';return}if(!names.length){state.textContent='没有识别到可写入的酒水销量。';return}if(result.unmatched.length){state.textContent='发现未匹配的酒水饮料，已阻止写入以避免漏单：'+result.unmatched.join('、')+'。请先完成品项映射。';return}if(result.invalid.length){state.textContent='发现 '+result.invalid.length+' 条无效品项，已阻止写入。';return}const previous=salesImportRecord(),next={fingerprint,businessDate:reportDate,source,sourceText,importedAt:new Date().toISOString(),items:names.length,total:result.total};if(previous?.fingerprint===fingerprint){state.textContent='这份美团销售明细已导入过，未重复写入。';return}if(previous&&!confirm('该日期已有不同的美团销售来源。确认用本次完整明细覆盖销量吗？'))return;rows.forEach(row=>{row.sales=Object.prototype.hasOwnProperty.call(result.matched,row.name)?result.matched[row.name]:0});persist();if(previous)recordSalesCorrection(previous,next);localStorage.setItem(salesImportKey(currentDate),JSON.stringify(next));render();state.textContent='已覆盖写入 '+currentDate+' 的完整销量：'+names.length+' 个品项、'+result.total+' 瓶；请只填写实物剩余库存，再保存日盘。';toastMsg('已写入完整美团销量')}
function importMeituanSales(){const input=document.getElementById('meituanSalesText'),dateInput=document.getElementById('meituanBusinessDate'),reportDate=dateInput?.value||'',sourceText=cleanSalesSourceText(input.value);writeMeituanSales(parseMeituanSales(sourceText),{reportDate,source:'meituan_text_manual_copy',sourceText})}
async function importMeituanSalesFile(input){const state=document.getElementById('meituanSalesResult'),file=input.files?.[0];if(!file)return;try{state.textContent='正在核对美团导出文件的营业日期和酒水品项…';const report=await parseMeituanXlsxFile(file);if(report.start!==report.end)throw Error('xlsx_date_range_invalid');const result=parseMeituanReportRows(report.items),sourceText=cleanSalesSourceText('美团品项销售统计导出：'+file.name+'\n'+report.filter+'\n酒水明细：\n'+report.items.filter(item=>canonicalSalesName(item.name)||isPossibleDrinkName(item.name)).map(item=>String(item.name||'')+' '+String(item.quantity??'')).join('\n'));if(report.start===YESTERDAY){localStorage.setItem(businessAnalysisKey(report.start),JSON.stringify({...buildBusinessAnalysis(report.items),businessDate:report.start,importedAt:new Date().toISOString()}));}writeMeituanSales(result,{reportDate:report.start,source:'meituan_xlsx_export',sourceText});renderManagementOverview?.()}catch(error){const messages={xlsx_file_required:'请选择美团管家导出的 .xlsx 文件。',xlsx_date_range_invalid:'该报表不是单个营业日，未写入。请在美团管家选择昨天 00:00:00–23:59:59 后重新导出。',xlsx_compression_unsupported:'当前浏览器不能读取该导出文件，请改用最新版 Chrome。',xlsx_layout_invalid:'未识别到美团“品项销售统计”的日期或销量列，未写入。'};state.textContent=messages[error?.message]||'读取导出文件失败，未写入任何销量。'}finally{input.value=''}}
function installMeituanSalesImporter(){if(document.getElementById('meituanSalesText'))return;const panel=document.querySelector('#waterPage .panel');if(!panel)return;const section=document.createElement('section');section.className='box';const options=rows.map(row=>'<option value="'+row.name+'">'+row.name+'</option>').join('');section.innerHTML='<div class="boxTitle">导入美团管家酒水销量</div><div class="hint">凌晨盘查只导入昨天完整营业日。优先选择美团管家“品项销售统计”导出的 .xlsx：系统会读取文件中的营业日期，只有昨天 00:00:00–23:59:59 的单日报表才会写入。无法导出时再粘贴酒水饮料明细。</div><label class="drop" for="meituanSalesFile"><input id="meituanSalesFile" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><strong>选择美团品项销售统计 .xlsx</strong><span>自动核验报表营业日期与未匹配酒水</span></label><div class="field" style="max-width:260px"><label>手工粘贴时的报表业务日期</label><input id="meituanBusinessDate" type="date"></div><textarea id="meituanSalesText" class="orderOutput" placeholder="青岛1903 9&#10;听可乐 13&#10;上海力波精酿白啤1L 5"></textarea><div class="rowBtns"><button class="btn blue" type="button">写入手工粘贴销量</button></div><div id="meituanSalesResult" class="result"></div><div class="boxTitle" style="margin-top:16px">新增酒水别名</div><div class="hint">遇到美团新名称或群内外号时，确认后在这里统一到盘点品名；不确定的名称不要添加。</div><div class="grid2"><div class="field"><label>别名</label><input id="salesAliasInput" maxlength="80" placeholder="例如：光明酸奶"></div><div class="field"><label>统一盘点品名</label><select id="salesAliasTarget">'+options+'</select></div></div><div class="rowBtns"><button class="btn" type="button">保存别名</button></div><div id="salesAliasResult" class="result"></div>';section.querySelector('#meituanBusinessDate').value=YESTERDAY;section.querySelector('#meituanSalesFile').addEventListener('change',event=>importMeituanSalesFile(event.target));const buttons=section.querySelectorAll('button');buttons[0].addEventListener('click',importMeituanSales);buttons[1].addEventListener('click',saveSalesAlias);panel.parentNode.insertBefore(section,panel)}
installMeituanSalesImporter();
