const SYNC_VERSION=1;
function legacyUpdateSyncStatus(){
  const filled=rows.filter(r=>Number(r.actual)>0).length;
  const cloudState=typeof cloudReady==='function'&&cloudReady()?(typeof cloudAuthenticated==='function'&&cloudAuthenticated()?'云端已登录':'云端待登录'):'本地模式（可导出数据包）';
  document.getElementById('syncStatus').textContent=`${cloudState}；当前日期：${currentDate}；共 ${rows.length} 个品项；已填写剩余库存 ${filled} 个。`;
}
function legacyAuditPackage(){return {version:SYNC_VERSION,type:'drink-audit',exportedAt:new Date().toISOString(),businessDate:currentDate,rows:rows.map(r=>({...r})),summary:{items:rows.length,sales:rows.reduce((a,r)=>a+n(r.sales),0),actual:rows.reduce((a,r)=>a+n(r.actual),0)}};}
function downloadAuditPackage(){const data=auditPackage(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`酒水盘查-${data.businessDate}.json`;a.click();URL.revokeObjectURL(url);document.getElementById('syncExportState').textContent=`已生成 ${data.businessDate} 的盘查数据包，可发给管理端导入。`;updateSyncStatus();}
async function copyAuditPackage(){try{await navigator.clipboard.writeText(JSON.stringify(auditPackage()));document.getElementById('syncExportState').textContent='数据包已复制，可直接发送给管理端。'}catch{document.getElementById('syncExportState').textContent='浏览器未授权复制，请使用“下载本次盘查数据包”。'}updateSyncStatus();}
async function legacySubmitAudit(){try{const uploaded=await uploadAuditToCloud();if(uploaded){document.getElementById('syncExportState').textContent='已提交云端，管理端可实时查看。';toastMsg('盘查已提交云端');}else downloadAuditPackage();}catch(error){document.getElementById('syncExportState').textContent=error.message==='cloud_auth_required'?'请先在“员工云端登录”完成身份验证。':error.message==='product_mapping_missing'?'云端品项字典未完成映射，未提交。':'云端提交失败，已保留本地数据，请使用数据包备份。';}}
async function legacyImportAuditPackage(input){const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data?.version!==SYNC_VERSION||data.type!=='drink-audit'||!/^\d{4}-\d{2}-\d{2}$/.test(data.businessDate)||!Array.isArray(data.rows)||!data.rows.length)throw Error('invalid');const safe=data.rows.map(r=>({name:String(r.name||'').slice(0,80),start:n(r.start),cases:n(r.cases),caseSize:n(r.caseSize),sales:n(r.sales),actual:n(r.actual)})).filter(r=>r.name);if(!safe.length)throw Error('empty');localStorage.setItem(key(data.businessDate),JSON.stringify(safe));localStorage.setItem(draftKey(data.businessDate),JSON.stringify(safe));document.getElementById('syncImportState').textContent=`已导入 ${data.businessDate}：${safe.length} 个品项，销量 ${data.summary?.sales??safe.reduce((a,r)=>a+n(r.sales),0)} 瓶。`;if(data.businessDate===currentDate){rows=safe;render();}updateSyncStatus();}catch{document.getElementById('syncImportState').textContent='导入失败：请选择由本系统生成的有效酒水盘查数据包。'}finally{input.value='';}}
function updateSyncStatus(){const filled=typeof actualEntryCount==='function'?actualEntryCount():rows.filter(r=>Number(r.actual)>0).length;const cloudState=typeof cloudReady==='function'&&cloudReady()?(typeof cloudAuthenticated==='function'&&cloudAuthenticated()?'云端已登录':'云端待登录'):'本地模式（可导出数据包）';document.getElementById('syncStatus').textContent=cloudState+'；当前日期：'+currentDate+'；共 '+rows.length+' 个品项；已明确盘点 '+filled+'/'+rows.length+' 个。';if(typeof renderManagementOverview==='function')renderManagementOverview()}
function auditPackage(){return {version:SYNC_VERSION,type:'drink-audit',exportedAt:new Date().toISOString(),businessDate:currentDate,actualEntered:[...actualEntryNames()],salesSource:typeof salesImportRecord==='function'?salesImportRecord(currentDate):null,salesCorrections:typeof salesCorrectionRecords==='function'?salesCorrectionRecords(currentDate):[],rows:rows.map(r=>({...r})),summary:{items:rows.length,sales:rows.reduce((a,r)=>a+n(r.sales),0),actual:rows.reduce((a,r)=>n(a)+reconciledActual(r),0)}};}
function importQuantity(value,{positive=false}={}){const parsed=Number(value);if(!Number.isFinite(parsed)||parsed<0||(positive&&parsed<=0))throw Error('quantity');return parsed}
async function importAuditPackage(input){const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data?.version!==SYNC_VERSION||data.type!=='drink-audit'||!/^\d{4}-\d{2}-\d{2}$/.test(data.businessDate)||!Array.isArray(data.rows)||!data.rows.length)throw Error('invalid');const allowed=new Set(BASE.map(row=>row.name));const safe=data.rows.map(row=>({name:String(row.name||''),start:importQuantity(row.start),cases:importQuantity(row.cases),caseSize:importQuantity(row.caseSize,{positive:true}),sales:importQuantity(row.sales),actual:importQuantity(row.actual),afterSales:importQuantity(row.afterSales),openTable:importQuantity(row.openTable)}));if(safe.length!==BASE.length||safe.some(row=>!allowed.has(row.name))||new Set(safe.map(row=>row.name)).size!==safe.length)throw Error('items');const entered=Array.isArray(data.actualEntered)?data.actualEntered.filter(name=>allowed.has(name)):[];localStorage.setItem(key(data.businessDate),JSON.stringify(safe));localStorage.setItem(draftKey(data.businessDate),JSON.stringify(safe));localStorage.setItem(actualEntryKey(data.businessDate),JSON.stringify([...new Set(entered)]));if(data.salesSource&&typeof data.salesSource==='object'&&typeof salesImportKey==='function'){const source={fingerprint:String(data.salesSource.fingerprint||'').slice(0,12000),businessDate:data.businessDate,source:String(data.salesSource.source||'imported_audit_package').slice(0,80),sourceText:typeof cleanSalesSourceText==='function'?cleanSalesSourceText(data.salesSource.sourceText):String(data.salesSource.sourceText||'').slice(0,12000),importedAt:String(data.salesSource.importedAt||''),items:importQuantity(data.salesSource.items||0),total:importQuantity(data.salesSource.total||0)};if(source.fingerprint)localStorage.setItem(salesImportKey(data.businessDate),JSON.stringify(source))}if(Array.isArray(data.salesCorrections)&&typeof salesCorrectionKey==='function'){const corrections=data.salesCorrections.slice(-20).filter(record=>record&&typeof record==='object').map(record=>({changedAt:String(record.changedAt||''),reason:String(record.reason||'').slice(0,80),previous:typeof sourceSummary==='function'?sourceSummary(record.previous):{},replacement:typeof sourceSummary==='function'?sourceSummary(record.replacement):{}}));localStorage.setItem(salesCorrectionKey(data.businessDate),JSON.stringify(corrections))}document.getElementById('syncImportState').textContent='已导入 '+data.businessDate+'：'+safe.length+' 个品项，销量 '+(data.summary?.sales??safe.reduce((sum,row)=>sum+n(row.sales),0))+' 瓶；明确盘点 '+new Set(entered).size+'/'+safe.length+' 个。';if(data.businessDate===currentDate){rows=safe;render()}updateSyncStatus()}catch{document.getElementById('syncImportState').textContent='导入失败：请选择由本系统生成、包含全部统一品项的有效数据包。'}finally{input.value=''}}
async function submitAudit(){const entered=actualEntryNames(),missing=rows.filter(row=>!entered.has(row.name)).map(row=>row.name);if(missing.length){document.getElementById('syncExportState').textContent='尚未明确填写 '+missing.length+' 个品项的剩余库存（含零库存）：'+missing.slice(0,6).join('、')+(missing.length>6?'…':'')+'。';return}try{const uploaded=await uploadAuditToCloud();if(uploaded){document.getElementById('syncExportState').textContent='已提交云端，管理端可实时查看。';toastMsg('盘查已提交云端');}else downloadAuditPackage();}catch(error){document.getElementById('syncExportState').textContent=error.message==='cloud_auth_required'?'请先在“员工云端登录”完成身份验证。':error.message==='product_mapping_missing'?'云端品项字典未完成映射，未提交。':'云端提交失败，已保留本地数据，请使用数据包备份。';}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
